### ISSUE TITLE
App doesn't provide filter functionality

### ISSUE THREAD

**Issue by Kaustubh-cribl** [volodk/logster#1]
Hi Volodymyr Krasnikov,

Thanks for taking time to work on the take home assignment & apologies for getting back a bit late.
I have gone through the submission but looks like the app doesn't provide an api with filtering capability.
I was wondering if that is something that can be implemented.

Thanks.

**Comment by volodk** [comment]
Good catch, I noticed that too ... after submitting the gh link :) 
Of cause it can be implemented. But I've got rejection email from your recruiting team already.

**Comment by Kaustubh-cribl** [comment]
Hello,

I apologize for the mis-communication and wish you the best for you next adventure!
Thank you!
